// fake data
const fakedata = [
  {
    id: 1,
    title: "Learn start to speak, read and understand French",
    instructorName: "Demarcus R. Barnes",
    instructorImg: "https://i.ibb.co/Bzgxtj7/instructor-1.jpg",
    price: 80,
    enrolled: 32,
    comment: 2,
    courseThumb:
      "https://i.ibb.co/2YygryY/Woman-hand-writing-Hello-Bonjour-on-green-blackboard.jpg",
    rating: 4.3,
  },
  {
    id: 2,
    title: "Be fluent & confident in Japanese",
    instructorName: "James R. Keiper",
    instructorImg: "https://i.ibb.co/kQtCyfM/instructor-2.jpg",
    price: 30,
    enrolled: 32,
    comment: 5,
    courseThumb:
      "https://i.ibb.co/WBnXNKs/Learn-Japanese-handwritten-in-the-notebook.jpg",
    rating: 4.7,
  },
  {
    id: 3,
    title: "Improve Your English Vocabulary",
    instructorName: "Christina M. Clark",
    instructorImg: "https://i.ibb.co/93Kcpg4/instructor-3.jpg",
    price: 19,
    enrolled: 26,
    comment: 0,
    courseThumb:
      "https://i.ibb.co/FqZQ5fN/Studying-and-learn-English-concept-Book-with-flag-of-Great-Britain-and-Big-Ben-tower-on-the-table-3d.jpg",
    rating: 3.7,
  },
  {
    id: 4,
    title: "Introduce and Describle Things",
    instructorName: "George K. Oliveros",
    instructorImg: "https://i.ibb.co/6sBcvW3/instructor-4.jpg",
    price: 65,
    enrolled: 27,
    comment: 12,
    courseThumb:
      "https://i.ibb.co/JrwmgNn/Shot-of-a-group-of-businesspeople-sitting-together-in-a-meeting.jpg",
    rating: 4,
  },
  {
    id: 5,
    title: "Enhance skills with speed reading",
    instructorName: "Joanne D. Ashton",
    instructorImg: "https://i.ibb.co/1KYrSc4/instructor-5.jpg",
    price: 65,
    enrolled: 10,
    comment: 1,
    courseThumb:
      "https://i.ibb.co/6w0sd0H/Businessman-and-alarm-clock-studio-shooting.jpg",
    rating: 3.5,
  },
  {
    id: 6,
    title: "All You Need to Speak German Fast",
    instructorName: "James G. Erickson",
    instructorImg: "https://i.ibb.co/KWPXd1P/instructor-6.jpg",
    price: 65,
    enrolled: 45,
    comment: 30,
    courseThumb:
      "https://i.ibb.co/tszXzhK/Learning-languages-concept-paper-with-text-sprechen-sie-deutsch-flag-of-the-Germany-books-headphones.jpg",
    rating: 5,
  },
  {
    id: 7,
    title: "Learn French for Bussiness and Leisure",
    instructorName: "Juana B. Martin",
    instructorImg: "https://i.ibb.co/4gyHB5r/instructor-8.jpg",
    price: 159,
    enrolled: 0,
    comment: 0,
    courseThumb: "https://i.ibb.co/RzGrBC9/course-7.jpg",
    rating: 0,
  },
  {
    id: 8,
    title: "Learn Englis rating: 4.7h with me – Grammar and Phrasal Verbs",
    instructorName: "Samuel A. Leung",
    instructorImg: "https://i.ibb.co/BGwHv0c/instructor-9.jpg",
    price: 69,
    enrolled: 50,
    comment: 33,
    courseThumb:
      "https://i.ibb.co/7kkhZCp/Distance-Education-Positive-lady-wearing-glasses-and-wireless-headest-at-virtual-meeting-sitting-at.jpg",
    rating: 4.2,
  },
  {
    id: 9,
    title: "Learn Japanese Writing System easier",
    instructorName: "David S. Williams",
    instructorImg: "https://i.ibb.co/09ycZ2D/instructor-7.jpg",
    price: 75,
    enrolled: 25,
    comment: 0,
    courseThumb:
      "https://i.ibb.co/DwLgghc/Learning-notes-written-in-Japanese-language-mathematics.jpg",
    rating: 3.7,
  },
  {
    id: 10,
    title: "A Complete Course for meeting people",
    instructorName: "Oscar L. Stalling",
    instructorImg: "https://i.ibb.co/jT1TQnp/instructor-10.jpg",
    price: 84,
    enrolled: 15,
    comment: 7,
    courseThumb:
      "https://i.ibb.co/wcPqL9F/Business-persons-with-protective-masks-during-a-meeting-in-the-office.jpg",
    rating: 2.9,
  },
  {
    id: 11,
    title: "Learn to speak like a native speaker",
    instructorName: "Joe D. Matthews",
    instructorImg: "https://i.ibb.co/KhMb38V/instructor-11.jpg",
    price: 35,
    enrolled: 20,
    comment: 5,
    courseThumb: "https://i.ibb.co/q0ZKNRb/course-11.jpg",
    rating: 3.3,
  },
  {
    id: 12,
    title: "Getting Started with LESS – Beginner Crash",
    instructorName: "Lila F. Snider",
    instructorImg: "https://i.ibb.co/p0pqWVz/instructor-12.jpg",
    price: 80,
    enrolled: 25,
    comment: 17,
    courseThumb:
      "https://i.ibb.co/cQp2TTG/At-the-women-s-health-conference-an-unidentified-speaker-explains-an-issue-that-affects-car-for-wome.jpg",
    rating: 4.9,
  },
];
